format_version: 3
environments:
  suse:
    environment_variables:
      STAGING_API: https://api.suse.de
pipelines:
  "SLE15.SP1.Staging.E":
    environment_variables:
      STAGING_PROJECT: SUSE:SLE-15-SP1:GA:Staging:E
    group: SLE15.SP1.Stagings
    materials:
      scripts:
        git: https://github.com/coolo/citest.git
    stages:
      - "Generate.Release.Package":
          approval: manual
          jobs:
            "Run.Pkglistgen":
              elastic_profile_id: "repo-checker"
              tasks:
                - exec:
                    command: ./generate-release-pkg.sh
      - "Check.Build.Succeeds":
          jobs:
            "Wait.For.Build":
              elastic_profile_id: "check-build"
              tasks:
                - script: ./check-build.sh
      - "Update.000product":
          jobs:
            "Run.Pkglistgen":
              elastic_profile_id: "check-build"
              tasks:
                - exec:
                    command: ./update-000product.sh
